************CODIGO CONSTRUCCION BASE DE DATOS*************

CREATE USER 'usr_admin'@'%' IDENTIFIED WITH caching_sha2_password BY '***';
GRANT ALL PRIVILEGES ON *.* TO 'usr_admin'@'%' WITH GRANT OPTION;ALTER USER 'usr_admin'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `BD_confeccionesunoa`.* TO 'usr_admin'@'%';


token ingreso git

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

token nuevo

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
